@startuml MyFinance-payable-component
title Payable Component

component "payable.py" {}

interface "/" as "enter_payable()"
interface "/payable/list/<vendor_number" as "get_payable_by_vendor(vendor_number)"
interface "/payable/<payable_id>" as "get_payable(payable_id)"
interface "/payable/edit/<payable_id>" as "edit_payable(payable_id)"
interface "/payable/payable_result" as "payable_result()"




@enduml